type User {
    id: ID
    name: String,
    email: String,
    tel: String,
    profile: Profile,
}

input UserInput {
    name: String,
    email: String,
    tel: String
}

type Query {
    user(id: Int): User
    users: [User]
}

type Mutation {
    createUser(data: UserInput): User!,

    updateUser(
        id: Int!,
        data: UserInput
    ): User!

}